---
name: supply-chain

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Test
        run: mvn --no-transfer-progress test

      - name: Build Image
        id: build
        uses: garethjevans/build-action@main
        with:
          # auth
          server: ${{ secrets.SERVER }}
          token: ${{ secrets.TOKEN }}
          ca_cert: ${{ secrets.CA_CERT }}
          namespace: ${{ secrets.NAMESPACE }}
          # image config
          destination: gcr.io/rawlingsj/github-actions-poc
          env: |
            BP_JAVA_VERSION=17

      - name: Scan Image
        run:
          echo "${{ steps.build.outputs.name }}"
